### PR TITLE
Feature/add controller inputs

### PR DESCRIPTION
**Pull request by eseer-divad**

### CODE REVIEW

**Comment by TwelveGem** [comment]
Can you give an explanation of what is on these changes.

**Comment by eseer-divad** [comment]
Overall: implemented python packaging in the RS_Package directory so that we can run some ROS nodes. Starting out, this is just the nodes for Joy, teleop_twist_joy, turtlesim, and a relay to rename 'cmd_vel' to '/turtle1/cmd_vel' (that's what turtlesim listens for)

Effect: allows people to run RS_Package with the run.sh script: 

```./RS_Package/run.sh --with-turtlesim``` => runs joy, teleop_twist_joy, & turtlesim for testing.

```./RS_Package/run.sh``` => runs joy & teleop_twist_joy, for publishing to Queue Package.

This does the default interpretation of Joy into a twist message, it does not implement the control schemes we desire, but it does offer a starting point with this current PR.

FILES:

- run.sh => runs the package as described above, 
- launch file => returns Joy, teleop_twist_joy, the relay, and turtlesim (turtlesim only runs if the flag above is present in the run command.)
- setup.py => defines directories and libraries to use to package and run RS
- package.xml => took out the CMake related dependencies and replaced everything with python counterparts.
- controller.config.yaml => defines a configuration for teleop_twist_joy.

**Review by TwelveGem — CHANGES_REQUESTED** [review]
I know that I already sent you a message about this, but I want to make sure that all the information is in one location. 

The purpose of ros launch is to be similar in effect to a shell script, but to do it for launching ros nodes. While having a script that builds everything is nice, this shouldn't be done inside of this folder. This would be done inside of the root folder so that way everything is built at the same time: colcon finds packages inside of folders.

**Comment by eseer-divad** [comment]
Delete run.sh entirely or move file upwards? Not a big deal to me at this point.

**Comment by TwelveGem** [comment]
So, it's been bugging me that we have nodes specifically for renaming topics. Let's say we have this happening everywhere we need it to happen. This would result in multiple topics publishing a `/cmd_vel` topic and it would get muddled up while trying to rename the topics. Instead of using this work around, let's use built in features, such as the remap function. I've been messing around a bit and have found something that I like with using a `xml` launch file

```xml
<launch>

    <arg name="use_turtlesim" default="false"/>

    <node
        pkg="turtlesim"
        exec="turtlesim_node"
        name="sim"
        if="$(var use_turtlesim)">

        <remap from="/turtle1/cmd_vel" to="/stupid/cmd_vel"/>
    </node>

    <node
        pkg="turtlesim"
        exec="turtlesim_node"
        name="stupid"
        unless="$(var use_turtlesim)">

        <remap from="/turtle1/cmd_vel" to="/thing/cmd_vel"/>
    </node>

</launch>
```

This isn't all the nodes that you have being started, but it is a start. I like this way much better than creating a python launch file. We're also able to have `if` and `unless` as tags in the creation of nodes where as I haven't  been able to find something similar to `unless` in python.

**Comment by eseer-divad** [comment]
I like this XML launch better as well just syntax wise, on top of that I didn't really consider the noise I'd create with all those topics. I'll work on this & building the control scheme code properly in the afternoon after my chem exam.

**Comment by TwelveGem** [comment]
I think that having 3 groups inside of the launch would be good (if we're continuing with a turtlesim debug area)
One that will always be running
One that will run if turtlesim
One that will run unless turtlesim

**Review by TwelveGem — APPROVED** [review]

**Review by TwelveGem — APPROVED** [review]

**Pull request merged**
